apiVersion: v1
kind: Pod
metadata:
  name: api-tester-4337
  namespace: anotherclass-433
  labels:
    instance: api-tester-4337
spec:
  nodeSelector:
    process: gpu
  tolerations:
    - key: nvidia
      value: V100
      operator: Equal
      effect: NoSchedule
  containers:
    - name: api-tester-4337
      image: 1pro/api-tester:3.0.0
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "200m"