apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-411
  name: api-tester-4111
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-4111
    version: 3.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-4111
  ports:
    - port: 80
      targetPort: http
  type: ClusterIP