apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-435
  name: core-4351
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: core
    instance: core-4351
    version: 4.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: core
    instance: core-4351
  ports:
    - port: 80
      nodePort: 30351
      targetPort: http
  type: NodePort