apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tester-4333
  namespace: anotherclass-433
spec:
  selector:
    matchLabels:
      instance: api-tester-4333
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        instance: api-tester-4333
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "resource"
                    operator: In
                    values: [low-spec, middle-spec]
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "resource"
                    operator: In
                    values: [low-spec, middle-spec]
      containers:
        - name: api-tester4333
          image: 1pro/api-tester:3.0.0
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"