apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-435
  name: cust-4351
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: cust
    instance: cust-4351
    version: 4.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: cust
    instance: cust-4351
  ports:
    - port: 80
      targetPort: http
  type: ClusterIP